### PR TITLE
Target netstandard.

### PR DESCRIPTION
**Pull request by mthamil**
This PR is for issue #1. The minimum version of Serilog has increased to 2.0.0. I don't have access to all of the build machinery really, so I left package creation using the old method.

### CODE REVIEW

**Comment by mthamil** [comment]
Hm, looks like the build config will have to change anyway.

**Comment by nblumhardt** [comment]
Thanks for having a shot!

The build can be updated by including an `appveyor.yml` file in the project root directory.

The content below is the current build exported from AppVeyor; modifying and including it should give you the ability to update the build.

```yml
version: '{build}'
build_script:
- ps: ./Build.ps1 -majorMinor "1.0" -patch "$env:APPVEYOR_BUILD_VERSION" -customLogger "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: Destructurama.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Db273rounfdesOqPXjqPrP6jeHGKkI52Rk+FSdnh6X/S6MuCelVFMpVMn67CcZgv
  on:
    branch: master
```

Cheers!

**Comment by nblumhardt** [comment]
The build scripts etc in https://github.com/destructurama/attributed have been updated to support the new tooling, so should be a good starting point. HTH!

**Comment by mthamil** [comment]
Ok, it may be good to go now. Thanks for your help.

**Comment by nblumhardt** [comment]
Looks good, thank you! 👍  I'm merging this to a new 'dev' branch, which should result in a 1.1.0 pre-release package being published to NuGet shortly.

**Comment by mthamil** [comment]
Awesome, thanks!

**Pull request merged**
